export type Lesson = { slug: string; label: string; title: string; summary: string; duration: string; steps: string[]; starterKit: string[]; isPreview?: boolean };

export const learningAreas = [
  { slug: "podcast", name: "Podcast", description: "De la idea a la publicación: formato, preparación, grabación y crecimiento." },
  { slug: "redes", name: "Contenido para redes", description: "Ideas, guiones, vídeo vertical y reutilización de contenido." },
  { slug: "video", name: "Vídeo", description: "Cámaras, móvil, luz, encuadre y flujos de grabación." },
  { slug: "audio", name: "Audio y locución", description: "Voz, micrófonos, grabación, edición y diseño sonoro." },
  { slug: "ia", name: "IA aplicada", description: "Herramientas para resolver tareas reales de creación de contenido." },
] as const;

export const lessons: Lesson[] = [
  { slug: "empezar-podcast-con-movil", label: "PRIMER PASO", title: "¿Puedo empezar un podcast con el móvil?", summary: "Sí. Antes de comprar nada, haz una prueba de voz en un sitio silencioso y descubre qué necesitas mejorar de verdad.", duration: "4 min", steps: ["Activa el modo avión y abre la app de notas de voz.", "Graba un minuto en una habitación con cortinas, ropa o libros cerca.", "Pon el móvil a unos 15 o 20 centímetros de tu boca, sin tapar el micrófono.", "Escucha con auriculares y apunta un único problema que quieras resolver en la siguiente prueba."], starterKit: ["Tu móvil", "Auriculares", "Una habitación tranquila"], isPreview: true },
  { slug: "primer-episodio-podcast", label: "PRIMER EPISODIO", title: "Qué contar en el primer episodio de tu podcast", summary: "No necesitas una gran presentación: explica de qué va el proyecto, para quién es y por qué merece la pena volver.", duration: "5 min", steps: ["Empieza con una frase que describa el tema y a quién acompañas.", "Cuenta qué encontrará la persona que te escuche y con qué frecuencia publicarás.", "Comparte un ejemplo, una historia o una pregunta que aterrice el primer tema.", "Cierra adelantando el siguiente episodio y con una invitación sencilla a seguirte."], starterKit: ["Una idea clara", "Un esquema de cuatro bloques", "Un temporizador"], isPreview: true },
  { slug: "duracion-ideal-podcast", label: "FORMATO", title: "¿Cuánto debería durar un episodio?", summary: "No hay una duración perfecta: elige el tiempo que tu idea necesita y que puedas sostener sin rellenar ni correr.", duration: "4 min", steps: ["Decide una sola promesa para cada episodio.", "Si hablas tú solo, prueba con 15 o 20 minutos antes de alargarlo.", "Si entrevistas, prepara bloques y deja espacio para que la conversación respire.", "Edita repeticiones y desvíos; no cortes las pausas que ayudan a entender."], starterKit: ["Una promesa por episodio", "Escaleta", "Tiempo de escucha de prueba"], isPreview: true },
  { slug: "podcast-con-video-o-solo-audio", label: "VIDEOPODCAST", title: "¿Podcast con vídeo o solo audio?", summary: "El vídeo puede ayudarte a descubrirte y sacar clips, pero no debe impedirte publicar un buen audio.", duration: "5 min", steps: ["Empieza por el audio: debe entenderse incluso sin mirar la pantalla.", "Elige vídeo si los gestos, una demostración o el espacio aportan algo a la conversación.", "Para la primera prueba basta un plano estable con el móvil y luz de ventana.", "Graba una versión sencilla y reutiliza los momentos claros en piezas cortas."], starterKit: ["Audio comprensible", "Móvil y trípode", "Luz natural"], isPreview: true },
  { slug: "publicar-podcast-spotify", label: "PUBLICACIÓN", title: "Cómo publicar tu podcast sin liarte con el RSS", summary: "Un alojamiento crea el feed RSS de tu programa; después lo envías a las plataformas donde quieres que aparezca.", duration: "6 min", steps: ["Prepara título, descripción breve, portada y un primer episodio terminado.", "Elige un servicio de alojamiento y completa los datos del programa.", "Copia la dirección de tu feed RSS desde el panel del alojamiento.", "Envía ese feed a Spotify y, si te interesa, a otros directorios; la aparición puede tardar hasta 24 horas."], starterKit: ["Portada cuadrada", "Descripción en tres frases", "Archivo final del episodio"], isPreview: true },
  { slug: "nombre-podcast-y-descripcion", label: "IDEA", title: "Cómo poner nombre y descripción a un podcast", summary: "Haz que alguien entienda en segundos qué ofreces: tema, público y un motivo concreto para darle al play.", duration: "5 min", steps: ["Escribe una frase: ‘Este podcast ayuda a [persona] a [resultado]’.", "Busca un nombre fácil de pronunciar, recordar y escribir.", "Evita títulos genéricos que no indiquen el tema ni tu enfoque.", "Redacta una descripción de hasta tres frases con palabras que usaría tu público al buscar."], starterKit: ["Una frase de propósito", "Cinco opciones de nombre", "Un amigo que no conozca la idea"], isPreview: true },
  { slug: "trabajar-audio-sin-agobios", label: "FLUJO DE TRABAJO", title: "Cómo trabajar el audio sin agobiarte", summary: "Un orden sencillo para no perder archivos, no repetir tareas y terminar episodios.", duration: "6 min", steps: ["Crea una carpeta por episodio con fecha y nombre claro.", "Guarda por separado los originales, el proyecto y las exportaciones finales.", "Primero arregla lo que molesta; después mejora lo que ya funciona.", "Antes de enviar, escucha una vez de principio a fin y revisa el nombre del archivo."], starterKit: ["Tres carpetas por episodio", "Una lista corta de tareas", "Una copia de seguridad"] },
  { slug: "voz-natural-en-microfono", label: "LOCUCIÓN", title: "Cómo sonar natural delante de un micrófono", summary: "No necesitas poner voz de radio: prepara el texto, respira y habla como le hablarías a una persona.", duration: "7 min", steps: ["No imites una voz que no es la tuya; busca claridad, no impostación.", "Marca en el texto dónde respirar y qué palabra quieres destacar.", "Haz tres tomas cortas en vez de perseguir una toma perfecta.", "Escucha una toma con distancia y corrige una sola cosa cada vez."], starterKit: ["Texto con anotaciones", "Agua", "Auriculares"] },
  { slug: "efectos-sin-liarla", label: "EFECTOS", title: "Usa efectos sin liarla", summary: "Aprende a colocar música y efectos como apoyo, sin tapar la voz ni llenar todo de ruido.", duration: "8 min", steps: ["Empieza por la voz: debe entenderse antes de añadir nada.", "Coloca un efecto solo si ayuda a situar, separar o cerrar una idea.", "Baja la música hasta que se note su ausencia, no hasta que compita con el texto.", "Deja pequeños silencios: también son parte del montaje."], starterKit: ["Una pista de voz", "Una música con licencia", "Dos o tres efectos, no veinte"] },
  { slug: "arreglar-rebote-habitacion", label: "SONIDO", title: "Reduce el rebote de una habitación antes de editar", summary: "La mejor limpieza se hace antes de grabar: cambia el espacio y evita depender de plugins.", duration: "5 min", steps: ["Aléjate de paredes vacías, ventanas grandes y mesas de cristal.", "Acércate al micro y baja la ganancia en lugar de subirla.", "Graba cerca de cortinas, ropa, sofá o estanterías llenas.", "Haz una prueba y compara antes de empezar la conversación real."], starterKit: ["Habitación con textiles", "Micrófono cerca de la voz", "Prueba de 20 segundos"] },
  { slug: "tu-podcast-no-va-a-petarlo", label: "ARCHIVO LOCAL RESET", title: "Tu podcast no va a petarlo a la primera", summary: "La guía para arrancar sin obsesionarte con los números: una buena idea, un plan sencillo y la primera publicación.", duration: "3 min", steps: ["Define en una frase qué quieres contar y a quién le puede interesar.", "Haz una lluvia de ideas y convierte las mejores en una primera temporada de 8 a 10 episodios.", "Prepara un esquema para cada episodio: la improvisación funciona mucho mejor cuando hay una base.", "Prueba tu voz grabando con el móvil y acostúmbrate a escucharte antes de publicar.", "Cuida lo técnico sin bloquearte: empieza con un set sencillo y mejora cuando el proyecto lo pida."], starterKit: ["Una libreta o documento de ideas", "El móvil para hacer pruebas", "Un calendario realista de episodios"] },
  { slug: "editar-audio", label: "EDICIÓN", title: "Edita el audio de tu podcast desde cero", summary: "Un flujo simple para pasar de una grabación larga a un episodio claro y agradable.", duration: "12 min", steps: ["Crea una copia de tu grabación y ponle un nombre con fecha.", "Escucha una vez y marca silencios largos, errores y repeticiones.", "Corta solo lo que distrae; deja respiraciones y pausas naturales.", "Ajusta el volumen de todas las voces antes de exportar."], starterKit: ["Un editor gratuito como Audacity o GarageBand", "Auriculares", "Una carpeta para guardar versiones"] },
  { slug: "grabar-audio-y-locucion", label: "LOCUCIÓN", title: "Graba una voz clara sin experiencia", summary: "Prepara tu espacio, tu voz y tus niveles para sonar natural desde la primera toma.", duration: "10 min", steps: ["Busca una habitación pequeña, silenciosa y con textiles.", "Coloca el micro a un palmo de tu boca y ligeramente de lado.", "Haz una prueba de 20 segundos y escucha con auriculares.", "Graba por frases: si te equivocas, vuelve a empezar la frase."], starterKit: ["Micrófono USB o móvil", "Auriculares", "Guion impreso o en pantalla"] },
  { slug: "microfonos", label: "MICRÓFONOS", title: "Elige tu primer micrófono para podcast", summary: "Entiende qué comprar según dónde grabas, cuántas personas sois y el presupuesto.", duration: "8 min", steps: ["Si grabas en casa sin tratar, empieza por un micrófono dinámico USB.", "Para una sola persona, prioriza facilidad de uso antes que muchos accesorios.", "Compra un soporte estable y una pantalla antipop antes de subir de gama.", "Prueba siempre el micro en tu habitación: el espacio importa más que la marca."], starterKit: ["Micrófono USB dinámico", "Soporte de mesa o brazo", "Filtro antipop"] },
  { slug: "tecnico-de-podcast", label: "TÉCNICO", title: "La parte técnica del podcast, explicada fácil", summary: "Conecta, revisa y organiza una grabación sin volverte técnico de sonido.", duration: "9 min", steps: ["Conecta todo antes de abrir el programa de grabación.", "Haz una prueba y deja el pico de voz cerca de -12 dB.", "Graba cada persona en una pista distinta si puedes.", "Guarda el proyecto, el audio original y la exportación en carpetas separadas."], starterKit: ["Ordenador o grabadora", "Cables revisados", "Lista corta de comprobación"] },
  { slug: "limpiar-audio", label: "SONIDO", title: "Limpia un audio sin destrozar la voz", summary: "Quita los problemas más evidentes con pocos ajustes y manteniendo una voz creíble.", duration: "11 min", steps: ["Primero corta golpes, tos y ruidos puntuales manualmente.", "Aplica reducción de ruido con suavidad y compara antes/después.", "Usa un filtro pasa-altos para reducir graves molestos.", "Si aparece un sonido metálico, deshaz el último ajuste: menos suele ser más."], starterKit: ["Audio original sin modificar", "Auriculares", "Editor con reducción de ruido"] },
  { slug: "ia-para-podcast", label: "IA", title: "Usa IA para preparar tu podcast", summary: "Convierte una idea en un guion, preguntas y piezas de difusión sin perder tu voz.", duration: "14 min", steps: ["Escribe en una frase para quién es el episodio y qué debe llevarse.", "Pide a la IA una estructura de bloques, no un guion cerrado.", "Convierte cada bloque en tres preguntas que dirías de forma natural.", "Reescribe la propuesta con tus ejemplos, opiniones y forma de hablar."], starterKit: ["Una idea de episodio", "Tu tono y referencias", "Un documento para revisar respuestas"] },
  { slug: "grabar-video", label: "VÍDEO", title: "Graba el vídeo de tu podcast con lo que ya tienes", summary: "Una configuración sencilla para que el vídeo acompañe al audio y se vea cuidado.", duration: "10 min", steps: ["Limpia la lente del móvil y graba en horizontal si vas a YouTube.", "Coloca la cámara a la altura de los ojos y evita el contraluz.", "Haz un plano general estable antes de pensar en más cámaras.", "Graba una claqueta o palmada para sincronizar vídeo y audio después."], starterKit: ["Móvil o cámara", "Trípode", "Espacio ordenado"] },
  { slug: "iluminacion-basica", label: "ILUMINACIÓN", title: "Ilumina tu podcast de forma básica", summary: "Haz que la cara se vea bien con una ventana o una sola luz, sin un set complicado.", duration: "7 min", steps: ["Colócate mirando hacia una ventana, nunca de espaldas a ella.", "Si no hay luz natural, usa una luz suave a 45 grados de tu cara.", "Aleja un poco la luz para evitar sombras duras.", "Apaga luces de techo que creen sombras bajo los ojos."], starterKit: ["Ventana o luz LED", "Difusor o cortina blanca", "Una pared o fondo limpio"] },
];

export const lessonBySlug = (slug: string) => lessons.find((lesson) => lesson.slug === slug);

export function lessonArea(slug: string) {
  if (["empezar-podcast-con-movil", "primer-episodio-podcast", "duracion-ideal-podcast", "podcast-con-video-o-solo-audio", "publicar-podcast-spotify", "nombre-podcast-y-descripcion", "tu-podcast-no-va-a-petarlo", "tecnico-de-podcast", "editar-audio", "microfonos"].includes(slug)) return "podcast";
  if (["grabar-video", "iluminacion-basica"].includes(slug)) return "video";
  if (slug === "ia-para-podcast") return "ia";
  return "audio";
}
