export const masterclassModules = [
  { slug: "idea-y-concepto", number: "01", title: "Idea y concepto", image: "https://www.localreset.com/assets/hero-electric/chico-madera-1280.webp", description: "Aterriza qué quieres contar y construye una idea que pueda sostenerse episodio tras episodio.", overview: ["En este módulo convertiremos una intuición en un podcast con dirección. Definiremos el tema, la persona a la que quieres hablar y el punto de vista que hace que tu propuesta no sea una más.", "Saldrás con una frase clara para explicar tu podcast y con un mapa de temas que te permita pensar en una primera temporada sin quedarte en blanco."], points: ["El objetivo del podcast", "A quién quieres hablar", "El concepto que une los episodios"] },
  { slug: "formato", number: "02", title: "Formato", image: "https://www.localreset.com/assets/hero-electric/podcast-vinyl-1280.webp", description: "Entrevista, conversación o podcast individual: encuentra el formato que encaja con tu idea y recursos.", overview: ["Veremos cuándo conviene hacer un podcast individual, una conversación entre dos personas o una entrevista. No se trata de copiar el formato que más ves, sino de elegir el que mejor sostiene tu idea y tu forma de comunicar.", "También revisaremos la duración, frecuencia y ritmo de publicación para que el formato sea realista con el tiempo y los recursos que tienes."], points: ["Formatos principales", "Qué exige cada uno", "Cómo elegir con criterio"] },
  { slug: "preparacion-y-guion", number: "03", title: "Preparación y guion", image: "https://www.localreset.com/assets/hero-electric/senor-doctor-1280.webp", description: "Prepara cada episodio para no depender de la improvisación.", overview: ["Aprenderás a preparar una escaleta que dé libertad sin convertir la grabación en un caos. Trabajaremos aperturas, bloques, cierres y las preguntas que hacen avanzar una conversación.", "Si invitas a alguien, veremos cómo investigar, contactar y preparar a esa persona para que llegue cómoda y con una conversación que merezca la pena escuchar."], points: ["Estructura y escaleta", "Preguntas y bloques", "Preparación de invitados"] },
  { slug: "microfonos-y-audio", number: "04", title: "Micrófonos y audio", image: "https://www.localreset.com/assets/hero-electric/studio-ladrillo-1280.webp", description: "Lo que necesitas realmente para conseguir un sonido claro y agradable.", overview: ["En este módulo conocerás y probarás distintos tipos de micrófono, desde opciones sencillas para empezar hasta equipos profesionales de estudio. Entenderás qué cambia entre ellos y cuál tiene sentido para tu espacio, tu voz y el formato que has elegido.", "Te enseñaremos a conectarlos, colocarlos y ajustar los niveles para grabar con seguridad. También practicaremos cómo tratar una habitación, qué errores provocan ruido o eco y qué revisar antes de darle a REC."], points: ["Tipos de micrófonos", "Conexiones, colocación y niveles", "Acústica y errores habituales"] },
  { slug: "camaras-y-video", number: "05", title: "Cámaras y vídeo", image: "https://www.localreset.com/assets/gallery/studio-08-1200.webp", description: "Plantea un videopodcast pensando en la grabación y en cómo se verá después.", overview: ["El vídeo no tiene por qué complicar tu podcast. Veremos qué puedes resolver con un móvil, cuándo merece la pena usar una cámara y cómo colocar cada plano para que la conversación se entienda y se vea natural.", "Trabajaremos encuadre, luz básica y continuidad para que puedas sacar un episodio completo y también clips útiles para YouTube y redes."], points: ["Cámaras y encuadres", "Luz básica", "YouTube y redes sociales"] },
  { slug: "grabacion", number: "06", title: "Grabación", image: "https://www.localreset.com/assets/gallery/studio-01-1200.webp", description: "Llevamos todo a la práctica: estudio, equipo y una grabación real de principio a fin.", overview: ["Aquí juntamos todo lo anterior en una sesión real. Prepararás el espacio, conectarás el equipo y pasarás por la lista de comprobación que evita la mayoría de los problemas antes de empezar.", "Después grabaremos de verdad: cómo dar una entrada, acompañar una conversación, detectar un fallo sin romper el ritmo y guardar los archivos para que edición tenga un buen punto de partida."], points: ["Preparar el estudio", "Configurar el equipo", "Trabajar durante la sesión"] },
  { slug: "edicion-y-publicacion", number: "07", title: "Edición y publicación", image: "https://www.localreset.com/assets/gallery/studio-06-1200.webp", description: "Cierra el proceso y entiende qué ocurre después de apagar los micros.", overview: ["Aprenderás un flujo de edición claro: ordenar el material, limpiar lo que distrae, mantener el ritmo de la conversación y exportar un archivo listo para escuchar. La idea es que sepas qué puedes resolver tú y cuándo pedir ayuda.", "Terminaremos viendo la publicación: título, descripción, portada, alojamiento, distribución y cómo convertir una grabación en piezas que puedas compartir sin rehacer el trabajo desde cero."], points: ["Edición y exportación", "Publicación y distribución", "Reutilizar el episodio"] },
] as const;
export const masterclassModuleBySlug = (slug: string) => masterclassModules.find((module) => module.slug === slug);
