import Link from "next/link";
import styles from "./MasterclassDetails.module.css";
import { masterclassModules } from "@/lib/masterclass";

const toolApps = [{ name: "Vocolia", icon: "⌁", description: "Ordena voces" }, { name: "Clipper", icon: "✂", description: "Encuentra clips" }, { name: "Rayo", icon: "ϟ", description: "Limpia audio" }, { name: "Faster", icon: "≫", description: "Acelera tareas" }];

export function MasterclassDetails() {
  return <><section id="masterclass-info" className={styles.learn}><div><small>QUÉ VAS A APRENDER</small><h2>Programa de la<br /><b>Masterclass.</b></h2></div><ol>{masterclassModules.map((module) => <li key={module.slug}><Link href={`/masterclass/${module.slug}`} className="masterclassModuleCard"><div className="masterclassModuleImage" style={{ backgroundImage: `linear-gradient(#080a1022,#080a1066),url('${module.image}')`, backgroundPosition: "center" }} /><span>{module.number}</span><b>{module.title}</b><p>{module.description}</p><em>Ver módulo →</em></Link></li>)}</ol></section><section className={styles.practice}><div><small>APRENDE HACIÉNDOLO</small><h2>Del podcast a<br /><b>tus propias herramientas.</b></h2><p>Aprenderás a usar Codex para crear pequeñas herramientas que resuelvan tareas reales de tu proyecto: convertir archivos, ordenar una biblioteca de audios, preparar una base de datos o automatizar procesos que ahora haces a mano.</p></div><div className={styles.practiceCard}><small>CODEX APLICADO A TU FLUJO</small><b>Diseña la herramienta profesional que necesitas, exactamente a tu gusto.</b><span>CONVERSORES · BASES DE DATOS · LIMPIEZA DE AUDIO · AUTOMATIZACIONES · UTILIDADES A MEDIDA</span></div><div className={styles.toolApps}>{toolApps.map((app) => <Link key={app.name} href="/registro" className={styles.toolApp} style={{ color: "inherit", textDecoration: "none" }} aria-label={`Crear cuenta para usar ${app.name}`}><article><div className={`${styles.appIcon} ${styles[app.name.toLowerCase()]}`}>{app.icon}</div><b>{app.name}</b><span>{app.description}</span></article></Link>)}</div></section><section className={styles.materials}><small>CUANDO TERMINE LA MASTERCLASS</small><h2>Tu biblioteca<br /><b>seguirá creciendo.</b></h2><p>Accederás a una zona privada con plantillas de guion, checklists, guías de cámara y sonido, recursos de edición, prompts y herramientas de IA. No será un PDF olvidado: iremos incorporando nuevos materiales y actualizaciones para tus proyectos.</p></section></>;
}
